services:
  - type: web
    name: smarthouse-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DB_URL
        sync: false
      - key: GIGACHAT_AUTH_DATA
        sync: false
      - key: USE_MOCK_AI
        value: "true"
      - key: MAX_TOKEN
        sync: false

  - type: web
    name: smarthouse-frontend
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: VITE_API_URL
        value: "https://smarthouse-backend.onrender.com"
